### ISSUE TITLE
[wso2mi 4.2.0]   [Continous Errors in carbon logs when pod count is > 1]

### ISSUE THREAD

**Issue by srinivaskancharla** [wso2/product-integrator-mi#3144]
Dears, 
Environment: 
wso2mi 4.2.0, JDK 17, Rocky 8.9(RHEL)

We have deployed the wso2mi with a wrapper  in k8s. 
Single pod instance we do not see any errors. But when the replica/pod count is increased to 2 we see below errors in logs.
Below errors are printing twice for every 5 seconds.

Logs:
[2024-02-07 10:23:27,878] ERROR

{SourceHandler}

- I/O error: Connection reset java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:482)
at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:544)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
at java.base/java.lang.Thread.run(Thread.java:840)

refer stackoverflow [link ](https://stackoverflow.com/questions/78078997/wso2mi-4-2-0-continous-socket-connection-errors-in-logs-when-pod-count-1)for better readability of INFO and DEBUG logs, kindly let us know what could be the problem.
@arunans23 could you pls re-direct to the correct team. Appreciate your support.

**Comment by chanikag** [comment]
Tested MI 4.6.0 with RHEL 9 and 10. Found no issues.
