### ISSUE TITLE
[Bug]: RabbitMQ Connection was not recovering when using MessageStoreMediator

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/product-integrator-mi#3450]
### Description

This issue occurred when attempting to publish a message to the RabbitMQ Broker. If an exception arose during this process, we tried to close the connection and set it to null to create a new connection. However, an AlreadyClosedException was thrown, preventing the MI from establishing a new connection.

```
[2024-07-23 13:11:16,216] ERROR {org.apache.synapse.message.store.impl.rabbitmq.RabbitMQProducer} - [NewQueue]. Ignored MessageId: <id> . Could not store message to store [NewQueue]. Error: connection is already closed due to connection error; cause: java.net.SocketException: Connection reset
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.net.SocketException: Connection reset
    at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
    at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
    at com.rabbitmq.client.impl.ChannelN.lambda$basicPublish$1(ChannelN.java:729)
    at com.rabbitmq.client.observation.NoOpObservationCollector.publish(NoOpObservationCollector.java:32)
    at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:731)
    at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:703)
    at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:693)
    at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:207)
    at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQProducer.publishMessage(RabbitMQProducer.java:177)
    at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQProducer.storeMessage(RabbitMQProducer.java:94)
    at org.apache.synapse.mediators.store.MessageStoreMediator.mediate(MessageStoreMediator.java:126)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
    at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
    at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69)
    at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
    at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
    at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:87)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

### Affected Version(s)

4.1.0

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/2186
